export type Product={id:string;name:string;subtitle:string;description:string;color:string;ink:string;price:number;weight:number;type:string;notes:string[];sweetness:number;cocoa:number;nuttiness:number;category:string};
export const products:Product[]=[
{id:'pistachio-bliss',name:'Pistachio Bliss',subtitle:'White chocolate with pistachio',description:'Creamy white chocolate meets the delicate, mellow crunch of pistachios.',color:'#8b9572',ink:'#273021',price:350,weight:80,type:'White',notes:['Creamy','Roasted','Delicate'],sweetness:4,cocoa:1,nuttiness:5,category:'signature-bars'},
{id:'nutty-harmony',name:'Nutty Harmony',subtitle:'Milk chocolate with mixed nuts',description:'A comforting meeting of smooth milk chocolate, almonds and cashews.',color:'#b98c3f',ink:'#332312',price:325,weight:80,type:'Milk',notes:['Buttery','Crunchy','Mellow'],sweetness:4,cocoa:2,nuttiness:5,category:'signature-bars'},
{id:'hazelnut-noir',name:'Hazelnut Noir',subtitle:'Dark chocolate with hazelnut',description:'Deep cocoa with a warm, toasted hazelnut finish. Made for slow moments.',color:'#ab6550',ink:'#392016',price:350,weight:80,type:'Dark',notes:['Toasted','Rounded','Rich'],sweetness:3,cocoa:4,nuttiness:5,category:'signature-bars'},
{id:'berry-delight',name:'Berry Delight',subtitle:'Chocolate with bright berry notes',description:'A bright berry note that unfolds against a silky chocolate backdrop.',color:'#944451',ink:'#f1d7bf',price:350,weight:80,type:'Fruity',notes:['Bright','Tangy','Silky'],sweetness:4,cocoa:3,nuttiness:1,category:'signature-bars'},
{id:'dark-fruit',name:'Dark Fruit',subtitle:'Dark chocolate with fruit',description:'Dark chocolate and deep fruit notes, with a beautifully lingering finish.',color:'#5b2d39',ink:'#e8c7aa',price:375,weight:80,type:'Fruity',notes:['Deep','Fruity','Lingering'],sweetness:3,cocoa:4,nuttiness:1,category:'signature-bars'},
{id:'intense',name:'Intense',subtitle:'Extra dark chocolate',description:'An uncompromising cocoa experience. Bold, beautifully dark and quietly complex.',color:'#292724',ink:'#d9b98e',price:375,weight:80,type:'Dark',notes:['Bold','Cocoa','Complex'],sweetness:1,cocoa:5,nuttiness:1,category:'signature-bars'}];
export const occasions=['Birthday','Anniversary','Wedding','Thank You','Congratulations','Festival','Corporate','Just Because'];
export const categories=['Signature Bars','Gift Boxes','Celebration Gifts','Corporate Gifts','Limited Editions'];
export const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
export const byId=(id:string)=>products.find(p=>p.id===id);
