'use client';
import {useEffect,useRef,useState} from 'react';
import {LiquidSculpture} from './liquid-sculpture';
import {ChocolateFlow} from './chocolate-flow';
import {GiftBox,Bar} from './packaging';
import {products} from '@/lib/catalog';
import {Snap} from './home';
const tests=['Realistic liquid chocolate flow','Chocolate from outside the screen','Chocolate crossing the screen','Chocolate covering the screen','Chocolate draining away','Chocolate drip transition','Logo liquid mask reveal','Gift box opening','Six chocolates leaving the box','Ingredient parallax','Chocolate snap','Build-a-box drop'];
function Test({index,name}:{index:number;name:string}){const[p,setP]=useState(0),[playing,setPlaying]=useState(false);const current=useRef(0);current.current=p;useEffect(()=>{if(!playing)return;let frame=0,last=performance.now();const tick=(t:number)=>{const next=Math.min(1,current.current+(t-last)/4000);last=t;setP(next);current.current=next;if(next<1)frame=requestAnimationFrame(tick);else setPlaying(false)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[playing]);return <article className="lab-card"><h2>{String(index+1).padStart(2,'0')} / {name}</h2><div className="lab-stage">{index<3?<LiquidSculpture progress={p}/>:index<6?<ChocolateFlow progress={p} mode={index===3?'cover':index===4?'drain':'drip'}/>:index===6?<><div className="lab-logo" style={{clipPath:`inset(0 ${100-p*100}% 0 0)`}}>VANORIA</div><ChocolateFlow progress={p}/></>:index<9?<GiftBox progress={p}/>:index===9?<div className="lab-ingredient" style={{transform:`translateY(${p*60}px) scale(${1+p*.2})`}}/>:index===10?<Snap controlled={p}/>:<><GiftBox progress={1} items={p>.9?[products[0].id]:[]}/><div className="lab-drop" style={{transform:`translateY(${p*190-60}px) rotate(${p*20}deg)`}}><Bar product={products[0]} small/></div></>}</div><div className="lab-controls"><button onClick={()=>setPlaying(true)}>Play</button><button onClick={()=>setPlaying(false)}>Pause</button><button onClick={()=>{setP(0);current.current=0;setPlaying(true)}}>Replay</button><button onClick={()=>{setPlaying(false);setP(0);current.current=0}}>Reset</button></div><input type="range" min="0" max="1" step=".001" value={p} aria-label={`${name} progress`} onChange={e=>{setPlaying(false);setP(Number(e.target.value))}}/><output>SCROLL PROGRESS: {p.toFixed(2)}</output></article>}
export function AnimationLab(){return <main className="content-page"><p className="eyebrow">VANORIA / DEVELOPMENT ONLY</p><h1 className="serif text-5xl">The chocolate atelier.</h1><p>Isolated motion studies. Drag each progress control in either direction. Packaging is sample artwork; fluid geometry and photographic texture transitions are separate studies.</p><a className="text-link" href="/">Back to the experience</a><div className="lab-grid">{tests.map((name,index)=><Test key={name} name={name} index={index}/>)}</div></main>}
