'use client';
import {useEffect,useRef,useState} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {motion} from 'framer-motion';
import {ArrowDown,ArrowUpRight,Plus} from 'lucide-react';
import {products,occasions} from '@/lib/catalog';
import {Header} from './store';
import {LiquidSculpture} from './liquid-sculpture';
import {ChocolateFlow} from './chocolate-flow';
import {GiftBox,Bar} from './packaging';
import {Shop,BoxBuilder,GiftFinder} from './commerce';
import {Footer} from './footer';
gsap.registerPlugin(ScrollTrigger);
export function useScrollScene(distance=1){const ref=useRef<HTMLDivElement>(null);const[p,setP]=useState(0);useEffect(()=>{const el=ref.current;if(!el)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){setP(1);return;}const state={p:0};const t=gsap.to(state,{p:1,ease:'none',scrollTrigger:{trigger:el,start:'top top',end:'bottom bottom',scrub:.7},onUpdate:()=>setP(state.p)});return()=>{t.scrollTrigger?.kill();t.kill()}},[distance]);return {ref,p}}
export function Snap({controlled}:{controlled?:number}){const[broken,setBroken]=useState(false);const b=controlled===undefined?broken:controlled>.5;return <section className="snap-section"><p className="eyebrow">THE SIMPLEST PLEASURES. EXTRAORDINARILY MADE.</p><h2>{b?<>The ingredients<br/><em>make the difference.</em></>:<>Break into<br/><em>something extraordinary.</em></>}</h2><button className={'snap-slab '+(b?'broken':'')} aria-label={b?'Put the chocolate back together':'Break the chocolate'} onClick={()=>setBroken(v=>!v)}><span className="snap-reveal">COCOA. CHARACTER. CARE.</span>{Array.from({length:6},(_,i)=><motion.span className="snap-piece" key={i} animate={{x:b?(i%3-1)*80:0,y:b?(i<3?-65:65):0,rotate:b?(i-2.5)*8:0}} transition={{type:'spring',stiffness:120,damping:17}} style={{backgroundImage:"url('/vanoria/textures/chocolate-slab.webp')",backgroundSize:'300% 200%',backgroundPosition:`${i%3*50}% ${i<3?0:100}%`}}/>)}{b&&Array.from({length:12},(_,i)=><motion.i className="crumb" key={i} initial={{x:0,y:0,opacity:1}} animate={{x:Math.cos(i)*200,y:Math.sin(i)*120,opacity:0}} transition={{duration:1}}/>)}</button><button className="snap-caption" onClick={()=>setBroken(v=>!v)}>{b?'A little wonder in every piece. Tap to reset.':'Go on. Give it a snap.'} <Plus size={13}/></button></section>}
function GiftScene(){const{ref,p}=useScrollScene();return <div ref={ref} className="scroll-chapter gift-chapter"><section className="gift-scene sticky-scene" id="gift"><LiquidSculpture progress={1}/><div className="gift-copy"><p className="eyebrow">01 / THE ART OF GIVING</p><h2>More than<br/><em>chocolate.</em></h2><p>A gift remembered<br/>long after the last piece.</p><a className="button" href="/shop">Explore the collection <ArrowUpRight size={17}/></a><a className="text-link" href="/build-your-box">Create a gift</a></div><div className="gift-object"><GiftBox progress={p}/><p className="asset-note">Sample gift-box design</p></div><span className="scene-instruction">{p<.65?'SCROLL TO UNWRAP SOMETHING WONDERFUL':'SIX PERSONALITIES. ONE BEAUTIFUL COLLECTION.'}</span><div className="scene-line"><span style={{width:p*100+'%'}}/></div></section></div>}
function Flavours(){const{ref,p}=useScrollScene();const index=Math.min(5,Math.floor(p*6));const active=products[index];return <div ref={ref} className="scroll-chapter flavour-chapter"><section className="flavour-world sticky-scene" style={{background:active.color,color:active.ink}}><div className="flavour-text"><p className="eyebrow">02 / SIX FLAVOURS. SIX LITTLE WORLDS.</p><span className="flavour-no">0{index+1} — 06</span><h2 key={active.name}>{active.name.split(' ').map((w,i)=><span key={w}>{i===1?<em>{w}</em>:w}</span>)}</h2><p>{active.subtitle}</p><a className="button" href={'/product/'+active.id}>Shop {active.name}<ArrowUpRight size={16}/></a></div><div className="flavour-object"><Bar product={active}/>{index===0&&<img className="ingredient-mood" src="/vanoria/ingredients/pistachio/mood.webp" alt="Pistachio kernels and shells"/>}</div><div className="flavour-ribbon"><LiquidSculpture foreground progress={1}/></div><div className="flavour-nav">{products.map((v,i)=><button key={v.id} className={i===index?'active':''} aria-label={'Explore '+v.name} onClick={()=>{const el=ref.current;if(el)window.scrollTo({top:el.offsetTop+(el.offsetHeight-innerHeight)*(i+.05)/6,behavior:'smooth'})}}><span style={{background:v.color}}/>{v.name}</button>)}</div></section></div>}
function LiquidTransition({drip=false}:{drip?:boolean}){const{ref,p}=useScrollScene();return <div ref={ref} className={'scroll-chapter transition-chapter '+(drip?'drip-chapter':'')}><section className="sticky-scene transition-stage"><div className="transition-under"><p className="eyebrow">{drip?'A GIFT AS INDIVIDUAL AS THEY ARE':'THE NEXT MOMENT IS YOURS'}</p><h2>{drip?<>Made for<br/><em>someone special.</em></>:<>A world of<br/><em>indulgence.</em></>}</h2></div><ChocolateFlow mode={drip?'drip':p<.5?'cover':'drain'} progress={drip?Math.sin(p*Math.PI):p<.5?p*2:(p-.5)*2}/></section></div>}
export function Occasions(){return <section className="occasions-section"><p className="eyebrow">FOR THE MOMENTS THAT MATTER</p><h2>Every reason.<br/><em>Every season.</em></h2><div className="occasion-editorial">{occasions.map((o,i)=><a key={o} href={'/occasions/'+o.toLowerCase().replaceAll(' ','-')} className={'occasion occasion-'+i}><span>0{i+1}</span><h3>{o}</h3><ArrowUpRight size={25}/></a>)}</div></section>}
export function Story(){const{ref,p}=useScrollScene();const words=['People.','Planet.','Pleasure.'];const idx=Math.min(2,Math.floor(p*3));return <div ref={ref} className="scroll-chapter story-chapter"><section className="sticky-scene story-section"><p className="eyebrow">THE THINGS WE COME BACK TO</p><h2>{words[idx]}</h2><p>{['The care of making. The joy of giving. The people who bring both to life.','Our sourcing story deserves detail. Verified ingredient origins and packaging information will be shared here.','A quiet moment for yourself. A beautiful surprise for someone else. Chocolate has a way of bringing us together.'][idx]}</p><div className="story-photo" style={{backgroundImage:`url('/vanoria/${idx===1?'ingredients/pistachio/mood.webp':'textures/chocolate-slab.webp'}')`}}/><div className="story-dots">{words.map((w,i)=><span key={w} className={idx===i?'active':''}>{w}</span>)}</div></section></div>}
function River(){const{ref,p}=useScrollScene();return <section ref={ref} className="river-section"><ChocolateFlow mode="river" progress={Math.max(.3,p)}/><span className="river-word crafted">Crafted.</span><span className="river-word gifted">Gifted.</span><span className="river-word shared">Shared.</span><div><p className="eyebrow">THOUGHTFULLY CRAFTED. BEAUTIFULLY DIFFERENT.</p><h2>VANORIA</h2><p>AN ARTISANAL CHOCOLATE HOUSE</p></div></section>}
export function Home(){const{ref,p}=useScrollScene();const[intro,setIntro]=useState(0);useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){setIntro(1);return;}let frame=0;const start=performance.now();const tick=(now:number)=>{const v=Math.min(1,Math.max(0,(now-start-900)/2300));setIntro(v);if(v<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[]);return <><Header/><main><div ref={ref} className="opening-chapter"><section className="opening sticky-scene"><div className="intro-motto">SIX FLAVOURS. A SWEETER TOMORROW.</div><LiquidSculpture progress={1}/><div className="hero-word" style={{clipPath:`polygon(${100-intro*100}% 0,100% 0,100% 100%,${Math.max(0,120-intro*150)}% 100%)`}}><p>AN INVITATION TO INDULGE</p><h1>VANORIA</h1><span>AN ARTISANAL CHOCOLATE HOUSE</span></div><div className="hero-foreground" style={{opacity:p,transform:`translateY(${p*50}%) rotate(${p*-10}deg)`}}><LiquidSculpture foreground progress={p}/></div><div className="hero-bottom"><p>A little wonder.<br/><em>A lasting impression.</em></p><a href="#gift" className="scroll-cue"><span>FOLLOW THE CHOCOLATE</span><ArrowDown size={18}/></a><span className="edition">CRAFTED WITH INTENTION<br/>SHARED WITH LOVE</span></div></section></div><GiftScene/><Flavours/><LiquidTransition/><Shop compact/><Snap/><LiquidTransition drip/><BoxBuilder/><GiftFinder/><Occasions/><section className="corporate-teaser"><p className="eyebrow">THE ART OF CORPORATE GIFTING</p><h2>Some gestures<br/><em>stay with you.</em></h2><a className="button" href="/corporate-gifting">Create a lasting impression <ArrowUpRight size={17}/></a></section><Story/><River/></main><Footer/></>}
