'use client';
import {createContext,useContext,useState,useEffect,useCallback,type ReactNode} from 'react';
import {products,money,byId} from '@/lib/catalog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Toaster,toast} from 'sonner';
import {Plus,Minus,Trash2,ShoppingBag,ArrowUpRight,Search,Menu,Heart} from 'lucide-react';
import {Bar} from './packaging';
import {Factory} from './factory';
import {AmbientLiquid} from './ambient-liquid';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {StoreContext,useStore,type BagItem} from './store-context';
export {useStore} from './store-context';
export function fly(origin:HTMLElement,target:HTMLElement,color='#422316'){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const a=origin.getBoundingClientRect(),b=target.getBoundingClientRect(),el=document.createElement('i');Object.assign(el.style,{position:'fixed',left:`${a.x+a.width/2}px`,top:`${a.y+a.height/2}px`,width:'24px',height:'30px',background:color,boxShadow:'inset 3px 3px 3px #ffffff30, 0 3px 8px #0005',zIndex:'100',pointerEvents:'none'});document.body.appendChild(el);el.animate([{transform:'translate(-50%,-50%) rotate(0) scale(1)'},{transform:`translate(${(b.x-a.x)/2}px,${(b.y-a.y)/2-70}px) rotate(100deg) scale(.8)`},{transform:`translate(${b.x-a.x-a.width/2+b.width/2}px,${b.y-a.y-a.height/2+b.height/2}px) rotate(200deg) scale(.3)`,opacity:.2}],{duration:620,easing:'cubic-bezier(.3,.6,.3,1)'}).finished.then(()=>el.remove());target.animate([{transform:'scale(1)'},{transform:'scale(1.15)'},{transform:'scale(1)'}],{duration:300,delay:400});}
export function StoreProvider({children}:{children:ReactNode}){const [bag,setBag]=useState<BagItem[]>([]),[wishlist,setWishlist]=useState<string[]>([]),[ready,setReady]=useState(false),[open,setOpen]=useState(false),[preparing,setPreparing]=useState<(Omit<BagItem,'quantity'>&{amount?:number})|null>(null),[factoryStage,setFactoryStage]=useState('Crafting your chocolate');
 useEffect(()=>{try{const b=JSON.parse(localStorage.getItem('vanoria-bag')||'[]');const w=JSON.parse(localStorage.getItem('vanoria-wishlist')||'[]');if(Array.isArray(b))setBag(b.filter(x=>typeof x.id==='string'&&Number.isFinite(x.price)&&Number.isInteger(x.quantity)&&x.quantity>0));if(Array.isArray(w))setWishlist(w.filter(x=>typeof x==='string'));}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready){try{localStorage.setItem('vanoria-bag',JSON.stringify(bag));localStorage.setItem('vanoria-wishlist',JSON.stringify(wishlist));}catch{}}},[bag,wishlist,ready]);
 const commit=useCallback((item:Omit<BagItem,'quantity'>&{amount?:number},origin?:HTMLElement)=>{setBag(b=>b.some(i=>i.id===item.id)?b.map(i=>i.id===item.id?{...i,quantity:Math.min(99,i.quantity+(item.amount||1))}:i):[...b,{...item,quantity:item.amount||1}]);const target=document.getElementById('bag-control');if(origin&&target)fly(origin,target);toast.success(`${item.name} added to your bag`,{action:{label:'View bag',onClick:()=>setOpen(true)}})},[]);
 useEffect(()=>{const mc=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!mc)return;const lifecycle=new AbortController();void Promise.resolve(mc.registerTool({name:'list_vanoria_products',title:'Explore Vanoria chocolates',description:'Read the sample Vanoria catalogue. Pricing and artwork await brand approval.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>products},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 const add=useCallback((item:Omit<BagItem,'quantity'>,origin?:HTMLElement,amount=1)=>{setPreparing({...item,amount});setFactoryStage('Crafting your chocolate');},[]);
 useEffect(()=>{if(!preparing)return;const a=setTimeout(()=>setFactoryStage('Wrapping a little wonder'),900);const b=setTimeout(()=>setFactoryStage('On its way to your bag'),1800);return()=>{clearTimeout(a);clearTimeout(b)}},[preparing]);
 const quantity=(id:string,n:number)=>setBag(b=>b.map(i=>i.id===id?{...i,quantity:Math.min(99,Math.max(0,n))}:i).filter(i=>i.quantity>0));
 return <StoreContext.Provider value={{bag,wishlist,ready,add,quantity,toggleWish:id=>setWishlist(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]),openBag:()=>setOpen(true)}}>{children}<AmbientLiquid/><Dialog open={!!preparing} onOpenChange={v=>{if(!v&&preparing){commit(preparing);setPreparing(null)}}}><DialogContent className="factory-dialog"><DialogTitle className="serif">A little magic in the making.</DialogTitle><DialogDescription>Preparing a preview of {preparing?.name}. No order is placed.</DialogDescription>{preparing&&<Factory colour={byId(preparing.id)?.color} onComplete={()=>{commit(preparing,document.getElementById('factory-status')||undefined);setPreparing(null)}}/>}<p id="factory-status" aria-live="polite">{factoryStage}</p><button className="text-link" onClick={()=>{if(preparing)commit(preparing);setPreparing(null)}}>Skip animation and add to bag</button></DialogContent></Dialog><Sheet open={open} onOpenChange={setOpen}><SheetContent className="bag-sheet"><SheetHeader><SheetTitle className="serif text-4xl">Your indulgences.</SheetTitle><SheetDescription>A little something wonderful.</SheetDescription></SheetHeader><BagContents/><a className="button solid" href="/checkout" onClick={()=>setOpen(false)}>Secure checkout <ArrowUpRight size={16}/></a></SheetContent></Sheet><Toaster position="bottom-right" theme="dark"/></StoreContext.Provider>}
export function Header(){const {bag,openBag}=useStore();const[menu,setMenu]=useState(false);return <><header className="site-header"><a className="wordmark" href="/">VANORIA<span>AN ARTISANAL CHOCOLATE HOUSE</span></a><nav><a href="/shop">The collection</a><a href="/build-your-box">The art of gifting</a><a href="/our-story">Our story</a></nav><div className="header-actions"><a aria-label="Search" href="/search"><Search size={19}/></a><a className="wishlist-icon" aria-label="Wishlist" href="/wishlist"><Heart size={18}/></a><button id="bag-control" aria-label={`Shopping bag, ${bag.reduce((s,i)=>s+i.quantity,0)} items`} onClick={openBag}><ShoppingBag size={19}/><span>{bag.reduce((s,i)=>s+i.quantity,0)}</span></button><button className="mobile-menu" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu size={20}/></button></div></header><Sheet open={menu} onOpenChange={setMenu}><SheetContent><SheetHeader><SheetTitle>Explore Vanoria</SheetTitle></SheetHeader><nav className="mobile-nav">{[['The collection','/shop'],['Build your box','/build-your-box'],['Find a gift','/gift-finder'],['Our story','/our-story'],['Corporate gifting','/corporate-gifting'],['Your account','/account']].map(([n,h])=><a key={h} href={h}>{n}</a>)}</nav></SheetContent></Sheet></>}
export function BagContents(){const{bag,quantity}=useStore();const sub=bag.reduce((s,i)=>s+i.price*i.quantity,0);return <div className="bag-content">{!bag.length?<div className="empty-state"><ShoppingBag size={40}/><h3>Your bag is waiting.</h3><p>Discover your next favourite.</p><a className="text-link" href="/shop">Explore the collection</a></div>:<>{bag.map(i=><article className="bag-row" key={i.id}>{byId(i.id)?<Bar product={byId(i.id)!} small/>:<span className="gift-thumb">V</span>}<div><h3>{i.name}</h3><p>{money(i.price)}</p><div className="quantity"><button aria-label={`Remove one ${i.name}`} onClick={()=>quantity(i.id,i.quantity-1)}><Minus size={14}/></button><span>{i.quantity}</span><button aria-label={`Add one ${i.name}`} onClick={()=>quantity(i.id,i.quantity+1)}><Plus size={14}/></button><button aria-label={`Remove ${i.name}`} onClick={()=>quantity(i.id,0)}><Trash2 size={14}/></button></div></div></article>)}<div className="totals"><p><span>Subtotal</span><span>{money(sub)}</span></p><p><span>GST & shipping</span><span>At checkout</span></p><p><strong>Total before shipping / tax</strong><strong>{money(sub)}</strong></p></div></>}</div>}
